# Generated by Django 3.2.3 on 2024-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Прикрепите фото рецепта', upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
