# Generated by Django 3.2.3 on 2024-04-01 07:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240329_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='reviews.recipe', verbose_name='Рецепты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientrecipes',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиентов должно быть больше 1.'), django.core.validators.MaxValueValidator(32000, 'Количество ингредиентов должно быть меньше 32000.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='reviews.recipe', verbose_name='Рецепты'),
            preserve_default=False,
        ),
    ]
